// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJHWjUJtZQjZjoZiWpQomrN0MVOicrVtk',
    appId: '1:562730922018:web:8fefad6d11fa775b2d5a7b',
    messagingSenderId: '562730922018',
    projectId: 'student-reminder-xx-16738',
    authDomain: 'student-reminder-xx-16738.firebaseapp.com',
    storageBucket: 'student-reminder-xx-16738.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3wUWA0kdC2Jztne70u2xmT4Dls7WfzMI',
    appId: '1:562730922018:android:42ff066b38e2384d2d5a7b',
    messagingSenderId: '562730922018',
    projectId: 'student-reminder-xx-16738',
    storageBucket: 'student-reminder-xx-16738.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqbuoXiEDUpRo_xG0_PSnudLkFfbaGrVk',
    appId: '1:679398022451:ios:c678bafb7af4e62183b246',
    messagingSenderId: '679398022451',
    projectId: 'reminder-5cb70',
    storageBucket: 'reminder-5cb70.firebasestorage.app',
    iosBundleId: 'com.example.studentRemeinderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJHWjUJtZQjZjoZiWpQomrN0MVOicrVtk',
    appId: '1:562730922018:web:b4fc75c8f53614152d5a7b',
    messagingSenderId: '562730922018',
    projectId: 'student-reminder-xx-16738',
    authDomain: 'student-reminder-xx-16738.firebaseapp.com',
    storageBucket: 'student-reminder-xx-16738.firebasestorage.app',
  );

}